/**
 *  Function "location" which RETURNS an HTML script which has been
 * interpolated with values from an object (locationObj) passed to it from arrays
 * generated by TipDataProvider.js. This HTML string will then  be added into 
 * the variable "tipHTMLRepresentation" which will be added to the DOM via 
 * contentelement.innerHTML in LocationList.js  (?)
 */

export const location = (locationObj) => {
    return `
    <div>
        <img class="destinations__img" src=${locationObj.image} alt="">
        <p>${locationObj.caption}</p>
    </div>
    `
  }