/**
 *  Function "Tip" which RETURNS an HTML script which has been
 * interpolated with values from an object (tipObj) passed to it from arrays
 * generated by TipDataProvider.js. This HTML string will then  be added into 
 * the variable "tipHTMLRepresentation" which will be added to the DOM via 
 * contentelement.innerHTML in TipList.js  (?)
 */

 export const Tip = (tipObj) => {
  return `
    <div class="tips__item">
        <p class="item__number">${tipObj.number}</p>
        <p class="item__text">${tipObj.text}</p>
    </div>  
  `
}